# Generated by Django 4.0.10 on 2023-09-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('api', '0002_alter_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='jobs',
            field=models.ManyToManyField(to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
