# Generated by Django 4.0.10 on 2023-09-26 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
        ('api', '0006_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels.level'),
        ),
    ]
