# Generated by Django 4.0.10 on 2023-09-26 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
        ('jobs', '0004_alter_job_name'),
        ('api', '0007_customuser_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='jobs',
            field=models.ManyToManyField(blank=True, null=True, to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='levels.level'),
        ),
    ]
